from app.services.llm.model_verify import verify_model_config
from app.services.llm.manage import (
    create_model,
    create_provider,
    delete_model,
    delete_provider,
    get_model,
    get_model_settings,
    get_or_create_settings,
    get_provider,
    list_models_paginated,
    list_providers_paginated,
    list_supported_providers,
    update_model,
    update_model_settings,
    update_provider,
)
from app.services.llm.resolver import (
    build_default_text_llm,
    build_chat_model_for_model,
    build_chat_model_from_provider,
    get_default_model_by_category,
    get_model_by_category,
    get_provider_by_id_or_obj,
    get_provider_by_model_or_id,
)
from app.services.llm.provider_bootstrap import bootstrap_builtin_providers
from app.services.llm.provider_registry import (
    ProviderSpec,
    get_provider_spec,
    list_registered_providers,
    register_many,
    register_provider,
    resolve_provider_key_from_name,
    try_resolve_provider_key_from_name,
)
from app.services.llm.provider_resolver import (
    ResolvedProviderConfig,
    resolve_provider_config,
    resolve_provider_config_by_model,
)

__all__ = [
    "verify_model_config",
    "create_model",
    "create_provider",
    "get_default_model_by_category",
    "delete_model",
    "delete_provider",
    "get_model_by_category",
    "get_model",
    "get_model_settings",
    "get_or_create_settings",
    "get_provider_by_id_or_obj",
    "get_provider_by_model_or_id",
    "get_provider",
    "list_models_paginated",
    "list_providers_paginated",
    "list_supported_providers",
    "update_model",
    "update_model_settings",
    "update_provider",
    "build_chat_model_for_model",
    "build_chat_model_from_provider",
    "build_default_text_llm",
    "ProviderSpec",
    "ResolvedProviderConfig",
    "bootstrap_builtin_providers",
    "get_provider_spec",
    "list_registered_providers",
    "register_many",
    "register_provider",
    "resolve_provider_key_from_name",
    "try_resolve_provider_key_from_name",
    "resolve_provider_config",
    "resolve_provider_config_by_model",
]
